[package]
name = "core-dev"
version = "0.0.1"
edition = "2021"
description = "core-dev library is an utility library for rust. It contains a lot of useful functions and APIs to speed up development cycle."
authors = [ "alexzanderr <alexzander.dot.dev@gmail.com>" ]
license = "MIT"
homepage = "https://github.com/alexzanderr/rust-core-dev"
repository = "https://github.com/alexzanderr/rust-core-dev"
documentation = "https://docs.rs/rust-core-dev"
readme = "README.md"
keywords = ["core", "development", "api"]
categories = ["accessibility"]



[dependencies]
reqwest = { version = "0.11.9", features = ["blocking"] }
doc-comment = "0.3.3"
default-args = "1.0.0"
globwalk = "0.8.1"
color-backtrace = "0.5.1"
color-eyre = "0.6.1"
ansi_term = { version = "0.12.1", features = [ "derive_serde_style", "serde" ] }
ansi-hex-color = "0.1.1"
hex_color = "1.0.0"
rand = "0.8.5"
bevy_reflect = "0.6.0"
bincode = "1.3.3"
string_template = "0.2.1"


[lib]
name = "core_dev"


[dev-dependencies]
rstest = "0.12.0"
pretty_assertions = "1.1.0"
